export const tags = [
  {
    name: 'Sternum',
    category: 'dragSec',
    style: {
      padding: '5px 10px',
      background: '#7A57D1',
      color: '#FFF',
      fontSize: '12px',
      marginBottom: '-20px',
    },
  },
  {
    name: 'Cranium',
    category: 'dragSec',
    style: {
      padding: '5px 10px',
      background: '#7A57D1',
      color: '#FFF',
      fontSize: '12px',
      marginBottom: '-20px',
    },
  },
  {
    name: 'Clavicle',
    category: 'dragSec',
    style: {
      padding: '5px 10px',
      background: '#7A57D1',
      color: '#FFF',
      fontSize: '12px',
      marginBottom: '-20px',
    },
  },
  {
    name: 'Ribs',
    category: 'dragSec',
    style: {
      padding: '5px 10px',
      background: '#7A57D1',
      color: '#FFF',
      fontSize: '12px',
      marginBottom: '-20px',
    },
  },
  {
    name: 'Humerus',
    category: 'dragSec',
    style: {
      padding: '5px 10px',
      background: '#7A57D1',
      color: '#FFF',
      fontSize: '12px',
      marginBottom: '-20px',
    },
  },
  {
    name: 'Ulna',
    category: 'dragSec',
    style: {
      padding: '5px 10px',
      background: '#7A57D1',
      color: '#FFF',
      fontSize: '12px',
      marginBottom: '-20px',
    },
  },
  {
    name: 'Radius',
    category: 'dragSec',
    style: {
      padding: '5px 10px',
      background: '#7A57D1',
      color: '#FFF',
      fontSize: '12px',
      marginBottom: '-20px',
    },
  },
  {
    name: 'Carpals',
    category: 'dragSec',
    style: {
      padding: '5px 10px',
      background: '#7A57D1',
      color: '#FFF',
      fontSize: '12px',
      marginBottom: '-20px',
    },
  },
  {
    name: 'PhalangesH',
    category: 'dragSec',
    style: {
      padding: '5px 10px',
      background: '#7A57D1',
      color: '#FFF',
      fontSize: '12px',
      marginBottom: '-20px',
    },
  },
  {
    name: 'Femur',
    category: 'dragSec',
    style: {
      padding: '5px 10px',
      background: '#7A57D1',
      color: '#FFF',
      fontSize: '12px',
      marginBottom: '-20px',
    },
  },
  {
    name: 'Tibia',
    category: 'dragSec',
    style: {
      padding: '5px 10px',
      background: '#7A57D1',
      color: '#FFF',
      fontSize: '12px',
      marginBottom: '-20px',
    },
  },
  {
    name: 'Fibula',
    category: 'dragSec',
    style: {
      padding: '5px 10px',
      background: '#7A57D1',
      color: '#FFF',
      fontSize: '12px',
      marginBottom: '-20px',
    },
  },
  {
    name: 'Tarsals',
    category: 'dragSec',
    style: {
      padding: '5px 10px',
      background: '#7A57D1',
      color: '#FFF',
      fontSize: '12px',
      marginBottom: '-20px',
    },
  },
  {
    name: 'PhalangesF',
    category: 'dragSec',
    style: {
      padding: '5px 10px',
      background: '#7A57D1',
      color: '#FFF',
      fontSize: '12px',
      marginBottom: '-20px',
    },
  },
  {
    name: 'Sacrum',
    category: 'dragSec',
    style: {
      padding: '5px 10px',
      background: '#7A57D1',
      color: '#FFF',
      fontSize: '12px',
      marginBottom: '-20px',
    },
  },
  {
    name: 'Pelvic',
    category: 'dragSec',
    style: {
      padding: '5px 10px',
      background: '#7A57D1',
      color: '#FFF',
      fontSize: '12px',
      marginBottom: '-20px',
    },
  },
  {
    name: 'Lumbar',
    category: 'dragSec',
    style: {
      padding: '5px 10px',
      background: '#7A57D1',
      color: '#FFF',
      fontSize: '12px',
      marginBottom: '-20px',
    },
  },
  {
    name: 'Thoracic',
    category: 'dragSec',
    style: {
      padding: '5px 10px',
      background: '#7A57D1',
      color: '#FFF',
      fontSize: '12px',
      marginBottom: '-20px',
    },
  },
  {
    name: 'Scapula',
    category: 'dragSec',
    style: {
      padding: '5px 10px',
      background: '#7A57D1',
      color: '#FFF',
      fontSize: '12px',
      marginBottom: '-20px',
    },
  },
  {
    name: 'Cervical',
    category: 'dragSec',
    style: {
      padding: '5px 10px',
      background: '#7A57D1',
      color: '#FFF',
      fontSize: '12px',
      marginBottom: '-20px',
    },
  },
]
