const style = {
  display: 'inline-block',
  whiteSpace: 'nowrap',
  padding: '5px 10px',
  background: '#7A57D1',
  color: '#FFF',
  fontSize: '12px',
  marginBottom: '-20px',
}

export const tags = [
  {
    name: 'Sternum',
    tag: 'Sternum',
    category: 'dragSec',
    style,
  },
  {
    name: 'Cranium',
    tag: 'Cranium',
    category: 'dragSec',
    style,
  },
  {
    name: 'Clavicle',
    tag: 'Clavicle',
    category: 'dragSec',
    style,
  },
  {
    name: 'Ribs',
    tag: 'Ribs',
    category: 'dragSec',
    style,
  },
  {
    name: 'Humerus',
    tag: 'Humerus',
    category: 'dragSec',
    style,
  },
  {
    name: 'Ulna',
    tag: 'Ulna',
    category: 'dragSec',
    style,
  },
  {
    name: 'Radius',
    tag: 'Radius',
    category: 'dragSec',
    style,
  },
  {
    name: 'Carpals',
    tag: 'Carpals',
    category: 'dragSec',
    style,
  },
  {
    name: 'Phalanges Hand',
    tag: 'PhalangesHand',
    category: 'dragSec',
    style,
  },
  {
    name: 'Femur',
    tag: 'Femur',
    category: 'dragSec',
    style,
  },
  {
    name: 'Tibia',
    tag: 'Tibia',
    category: 'dragSec',
    style,
  },
  {
    name: 'Fibula',
    tag: 'Fibula',
    category: 'dragSec',
    style,
  },
  {
    name: 'Tarsals',
    tag: 'Tarsals',
    category: 'dragSec',
    style,
  },
  {
    name: 'Phalanges Foot',
    tag: 'PhalangesFoot',
    category: 'dragSec',
    style,
  },
  {
    name: 'Sacrum Coccyx',
    tag: 'SacrumCoccyx',
    category: 'dragSec',
    style,
  },
  {
    name: 'Pelvic Girdle',
    tag: 'PelvicGirdle',
    category: 'dragSec',
    style,
  },
  {
    name: 'Lumbar Vertebrae',
    tag: 'LumbarVertebrae',
    category: 'dragSec',
    style,
  },
  {
    name: 'Thoracic Vertebrae',
    tag: 'ThoracicVertebrae',
    category: 'dragSec',
    style,
  },
  {
    name: 'Scapula',
    tag: 'Scapula',
    category: 'dragSec',
    style,
  },
  {
    name: 'Cervical',
    tag: 'Cervical',
    category: 'dragSec',
    style,
  },
]
